openapi: 3.0.0

info:
  title: immerse Rest APIs
  description: APIs used by immerse
  version: 1.0.0
  contact:
    email: 764647954@qq.com

servers:

tags:
  - name: immerse
    description: operations for immerse
  - name: login
    description: 登录管理

#接口-------------------------------------------------------------------------------------------------------------------
paths:
  /test:
    post:
      tags:
        - test
      description: 测试
      operationId: Test
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/test'
      responses:
        '200':
          description: 'category response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response_object'
        '400':
          $ref: '#/components/responses/bad_request'
        '401':
          $ref: '#/components/responses/unauthorized'
        '404':
          $ref: '#/components/responses/not_found'
        '5XX':
          $ref: '#/components/responses/server_error'

#参数-------------------------------------------------------------------------------------------------------------------
components:

  responses:
    success:
      description: General success response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/general'
    bad_request:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
    not_found:
      description: The specified resource was not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
    unauthorized:
      description: Unauthrized access
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
    server_error:
      description: Server internal error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'

  schemas:
    error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
        message:
          type: string
        type:
          type: string
        errors:
          type: array
          items:
            type: string

    general:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
        message:
          type: string

    #请求参数

    test:
      type: object
      required:
      properties:
        id:
          type: integer
          format: uint64
          example: 1

    response_object:
      type: object
      required:
      properties:
        code:
          type: integer
        msg:
          type: string
          format: int64
        data:
          type:
        count:
          type: integer
          format: int64
        id:
          type: string
        requestId:
          type: string

